# Generated by Django 6.0.2 on 2026-03-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_question_created_at_question_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_options',
            field=models.JSONField(default=list),
        ),
    ]
